"use client";
import { AuthContextProvider } from "@/context/AuthContext";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import ThemeRegistry from "./ThemeRegistry";

const poppins = Poppins({ weight: ["500", "600", "700", "800"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ThemeRegistry options={{ key: "mui" }}>
          <AuthContextProvider>{children}</AuthContextProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
